clone_depth: 5

environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - node_modules

install:
  - ps: Install-Product node 7.8.0 x64
  - npm install -g npm vsce > log.txt
  - npm install >> log.txt

build_script:
  - npm run compile

artifacts:
  - path: '**\*.vsix'

test_script:
  - node --version
  - npm --version
  - npm run test
